### ISSUE TITLE
Add link to discourse

### ISSUE THREAD

**Issue by alicetragedy** [cloudfleet/landing-page-2#3]
As of now, we have links to twitter and facebook on our landing page, but not to discourse. It would be great to add a link with a small icon there as well to try and get more traffic to our conversations.

**Comment by easye** [comment]
@alicetragedy Agreed.  We are probably gonna redo the framework as Angular while we can, probably making a 'landing-page-3' pulled from https://github.com/digitalhobo/commercial.

But if you make any edits here, I can easily merge them to work, so go ahead, branch, and add stuff so we can comment back and forth.

**Comment by easye** [comment]
To record what we discussed at the All-Hands:  the 'v3' branch contains the re-write in Angular.  It would be best for all changes to go on that branch (or a further branch of your own).  @metakermit and I are still working over the code to run under various incarnations NPM cleanly (I currently get warnings that get treated as errors), but some future descendant of https://github.com/cloudfleet/landing-page-2/tree/v3 will be what we push before CCC.

**Comment by metakermit** [comment]
I did some changes to the v3 branch to try to bring it more up to par with v2. Some commits we had on v2 were missing. It's closer to being usable, but still some way off. There are no errors when loading static files any more, even when running the minified version from the _dist/_ folder (the output of `grunt build`), but I think not all the styles or JS scripts were copied over yet. E.g. the page is spread over the whole width of my wide screen (https://www.dropbox.com/s/iz43qz8isuprajf/Screenshot%202015-12-12%2001.55.02.png?dl=0), unlike the current v2 cloudfleet.io (https://www.dropbox.com/s/8t9124gaalflywh/Screenshot%202015-12-12%2001.55.40.png?dl=0). Also, some animations are missing that we have in v2. The problem here is I don't know where to look for these styles / animations. Maybe it would be best if you could take another look, @digitalhobo, and see if you can finish the transition of these last few things.

Hopefully the `grunt build` errors you were experiencing, @easye, should be gone now (turns out I also had them, but I was always running `grunt serve`, not `grunt build`). It was an issue that was fixed with a newer version of the grunt-contrib-imagemin package.

@metakermit : Were you zoomed out in v2. what res is your screen. Emile.

**Comment by digitalhobo** [comment]
I can have a look at it on thursday and finish off whats need bud.
:0)

**Comment by metakermit** [comment]
Hey, Emile! Cool, that would be great! If you mange to get it done by noon
on Thursday, I can then set our deployment scripts to deploy the new
version live for the next meeting. You can get to the code by cloning the
landing-page-2 git repo and checking out the v3 branch:

git checkout v3

# make changes

git push -u origin v3

Please also take a look at the grunt build output in the dist/ folder (you
can just load that folder using a static html server, like python -m
SimpleHTTPServer ). The main glitches I spotted are that the main part now
expands over the whole screen with no margins (or is that intentional?) and
the orange arrow to go down to #simple-ui doesn't do anything.

**Comment by alicetragedy** [comment]
@digitalhobo :+1: I've assigned this issue to you if that's okay (that's what you meant, right?)

**Comment by digitalhobo** [comment]
yup, cheers alice :0)

**Comment by metakermit** [comment]
The Discourse link is finally up. Thanks for your patience, @alicetragedy :) Also, thanks for your help in getting the Angular page to be fully compatible with the old LP, @digitalhobo !

@easye https://cloudfleet.io/#/technology is ours for the conquering ;)

Also, cross-post from our internal ticket:

The new landing page in Angular is up. master is now equal to v3, so continue working on master as the main branch. I updated the order script to work in Angular too. I also created a template for the new technical alternative landing page at https://cloudfleet.io/#/technology . For reference, the old landing page is still available in v2 if someone still needs access to it.

I also updated the README with instructions on how to deploy the landing page.

https://github.com/cloudfleet/landing-page-2
